### ISSUE TITLE
Issues with moving to this service

### ISSUE THREAD

**Issue by ledpup** [HugoVG/CurrentDevice#2]
Hi,

I just switched to your library after using https://github.com/arivera12/BlazorCurrentDevice, because of https://github.com/arivera12/BlazorCurrentDevice/issues/5.

I've gotten it working but I had a couple of issues. They were:

- In the readme, it says `@using CurrentDevice` but it should be `@using BlazorCurrentDevice`
- I was using the service in two components. If I called the service twice to see if it's a mobile device or not, the first time it calls fine without issue. After that it throws an exception saying the key (Android) is already added. I got around this by only making the call once and then pusing the "IsMobileDevice" parameter through to the components I wanted.

Otherwise, looks like it's working well. Thanks!

**Comment by ledpup** [comment]
For anyone interested, my PR to switched between libraries: https://github.com/ledpup/ClimateExplorer/pull/407

**Comment by HugoVG** [comment]
Oh let me fix that real quick, thanks for reporing

**Comment by HugoVG** [comment]
Hopefully this fixes it.
